# Generated by Django 4.0.5 on 2022-06-30 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DockerAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uri', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(max_length=200)),
                ('uuid', models.UUIDField()),
                ('created', models.DateTimeField()),
                ('size', models.IntegerField()),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Containers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('command', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('status', models.CharField(choices=[('created', 'created'), ('running', 'running'), ('restarting', 'restarting'), ('exited', 'exited'), ('paused', 'paused'), ('dead', 'dead')], max_length=100)),
                ('ports', models.JSONField()),
                ('names', models.CharField(max_length=200)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.images')),
            ],
        ),
    ]
