# Generated by Django 3.2.13 on 2022-06-30 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DockerAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uri', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Docker Addresses',
                'verbose_name_plural': 'Docker Addresses',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository', models.CharField(max_length=200)),
                ('imageid', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField()),
                ('size', models.IntegerField()),
                ('tag', models.CharField(max_length=200)),
                ('docker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dockeraddresses')),
            ],
            options={
                'verbose_name': 'Images',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Containers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containerid', models.CharField(max_length=200, unique=True)),
                ('command', models.CharField(max_length=200)),
                ('created', models.DateTimeField()),
                ('status', models.CharField(choices=[('created', 'created'), ('running', 'running'), ('restarting', 'restarting'), ('exited', 'exited'), ('paused', 'paused'), ('dead', 'dead')], max_length=100)),
                ('ports', models.JSONField(blank=True, null=True)),
                ('names', models.CharField(max_length=200)),
                ('docker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dockeraddresses')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.images')),
            ],
            options={
                'verbose_name': 'Containers',
                'verbose_name_plural': 'Containers',
            },
        ),
    ]
