# Generated by Django 4.0.5 on 2022-06-30 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='containers',
            name='docker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.dockeraddresses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='docker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.dockeraddresses'),
            preserve_default=False,
        ),
    ]
