# Generated by Django 4.0.5 on 2022-06-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_containers_docker_images_docker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='containers',
            options={'verbose_name': 'Containers', 'verbose_name_plural': 'Containers'},
        ),
        migrations.AlterModelOptions(
            name='dockeraddresses',
            options={'verbose_name': 'Docker Addresses', 'verbose_name_plural': 'Docker Addresses'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Images', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterField(
            model_name='containers',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='dockeraddresses',
            name='uri',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
