# Generated by Django 4.0.5 on 2022-06-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_containers_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containers',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='images',
            name='uuid',
        ),
        migrations.AddField(
            model_name='containers',
            name='containerid',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='imageid',
            field=models.CharField(default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
