# Generated by Django 4.0.5 on 2022-06-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_containers_uuid_remove_images_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containers',
            name='ports',
            field=models.JSONField(null=True),
        ),
    ]
