# Generated by Django 4.0.5 on 2022-06-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_containers_ports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containers',
            name='ports',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
